import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '@/lib/registry'
import HeaderSignInSignIn from '@/components/HeaderSignInSignIn/HeaderSignInSignIn'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '+ Flavor',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <HeaderSignInSignIn />

          {children}
          
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}